name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - uses: ZenVoich/setup-mops@v1
        with:
            mops-version: 2.8.1
            identity-pem: ${{ secrets.MOPS_IDENTITY_PEM }}

      - name: Install dependencies
        run: mops install --lock ignore

      # - name: Detect warnings
      #   run: make check

      - name: Run Tests (MemoryBuffer)
        run: mops test MemoryBuffer

      - name: Run Tests (MemoryQueue)
        run: mops test MemoryQueue

      - name: Run Tests (MemoryBTree)
        run: mops test MemoryBTree

      - name: Run Tests (NodeCapacity)
        run: mops test nodecapacity 

      - name: Run Tests (PrefixCompression)
        run: mops test PrefixCompression
